### ISSUE TITLE
Code entry not showing numbers in ios

### ISSUE THREAD

**Issue by JArmandoCl** [HorusSoftwareUY/MaterialDesignControlsPlugin#46]
Hi! Thanks for this awesome plugin, actually in ios the code entry is not showing the numbers typed, android works well.

I have an iphone 8 ios 15.4.1.
Thanks!

**Comment by AgustinBonilla** [comment]
We are excited to announce that we are working on a new generation of controls based on Material Design V3, which we will be releasing soon.
This ticket has been included/fixed in the upcoming version of this NuGet package, which will include both current and new generations of controls.
Your feedback is greatly appreciated. Thank you for being part of our journey!
Feel free to open this issue again if it continues giving problems in the following version that we will be releasing soon!
