### ISSUE TITLE
IOS Renderers Separator is null,Please fix it as soon as possible. Thanks

### ISSUE THREAD

**Issue by Dadingtn** [HorusSoftwareUY/MaterialDesignControlsPlugin#47]
![image](https://user-images.githubusercontent.com/32587757/172341499-1e52c7b4-b58a-4ef3-8bd6-ed2e22b73166.png)

**Comment by AgustinBonilla** [comment]
We are excited to announce that we are working on a new generation of controls based on Material Design V3.
This ticket has been included/fixed in the upcoming version of this NuGet package, which will include both current and new generations of controls.
Your feedback is greatly appreciated. Thank you for being part of our journey!
