### ISSUE TITLE
MaterialPicker doesn't get updated when using MVVM

### ISSUE THREAD

**Issue by fdmomtaz** [HorusSoftwareUY/MaterialDesignControlsPlugin#49]
The MaterialPicker doesn't get updated when the MVVM value for the binding of the ItemsSource changes. The expected behavior is to have picker with updated values.

The material picker picker list does get updated if the when the view loads but fails to update when there are changes.

The code to reproduce:
XAML:
```
<material:MaterialPicker x:Name="PickerName" LabelText="Test" SelectedItem="{Binding TestValue}" ItemsSource="{Binding TestList}" />
```

ModelView:
```
// MVVM Variable
private ObservableCollection<string> testList = new ObservableCollection<string>(new List<string> { "Select Value" });
public ObservableCollection<string> TestList
{
    get { return testList; }
    set { if (testList == value) return; testList = value; }
}

private string testValue;
public string TestValue
{
    get => testValue;
    set
    {
        testValue = value;
        OnPropertyChanged();
    }
}

// updating the Variable
for (int I =0; I < 100; I++)
    TestList.Add("Value " + I);
```

**Comment by AgustinBonilla** [comment]
We are excited to announce that we are working on a new generation of controls based on Material Design V3.
This ticket has been included/fixed in the upcoming version of this NuGet package, which will include both current and new generations of controls. 
Your feedback is greatly appreciated. Thank you for being part of our journey!
